### ISSUE TITLE
Bug: All pages show the  "Wiki Page Template" as previous page

### ISSUE THREAD

**Issue by hmccarty** [purdue-arc/wiki#14]
**Description**

If you click on a page and scroll to the bottom, you will see a listing of the previous and next pages. It should follow the section order, however at the moment it only seems to show the "Wiki Page Template" as the previous page.

**Screenshots (If Necessary)**

![image](https://user-images.githubusercontent.com/23105519/122645031-bf412700-d0dd-11eb-8feb-2875c78b6377.png)

**Environment (If Necessary)**

Browser: Chrome

**Comment by raghavauppuluri13** [comment]
resolved
